### ISSUE TITLE
Run new line to break on all meta?

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/Rest-Easy#12]
How do you feel about running all meta fields through nl2br() before they make their way to JS? Is there ever a use case where you wanted to preserve the `\n` characters on the frontend? Anytime I do a "custom credits" thing, I like to do it as a `textarea`, and JS doesn't have a nice `nl2br` replacement (seems perfect for lodash if someone wants to commit that)

**Comment by jrobson153** [comment]
Adding to vuepress wishlist
