### ISSUE TITLE
Unix Time stamp off

### ISSUE THREAD

**Issue by lwaldner** [funkhaus/Rest-Easy#17]
In order to convert the unix time stamp provided by rest-easy you first need to multiply it by 1000 before passing it to the js Date constructor. 

Based on this post -> https://stackoverflow.com/questions/847185/convert-a-unix-timestamp-to-time-in-javascript it seems like the issue is that the time stamp provided by rest-easy is in seconds when the js Date constructor expects it to be in milliseconds

**Comment by SaFrMo** [comment]
@jrobson153 Is this something we should add an extra field for? Maybe have the current one be "unixTimeStamp" and the multiplied-by-1000 version "jsTimeStamp"?

**Comment by drewbaker** [comment]
Nah, I don't think it's worth adding that. Seems fine to just do some  simple math in JS.

This is why I want to have an examples of common filters (one of my proposed examples was a formatted date/time one).
