### ISSUE TITLE
Label output type

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/Rest-Easy#18]
Thinking through [this response](https://github.com/funkhaus/vuepress/issues/73#issuecomment-366331410), I realized we don't have a way to differentiate one type of Rest-Easy serialized object from another at a glance. 

I'm thinking we add a `type` property to each kind of result set to the name of the serializer used to create that result. Any objections @jrobson153 ?

**Comment by drewbaker** [comment]
Shouldn't we just add a "postType" parameter to each one? That would actually be useful for other things too.

**Comment by jrobson153** [comment]
Yea, serializing the post type for all objects is the way to do it. Surprised we didn't have that in there already!

**Comment by SaFrMo** [comment]
Added in 9b3e453
