### ISSUE TITLE
rez_gather_related not including children

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/Rest-Easy#20]
This will only consist of `siblings`:
`$related = apply_filters('rez_gather_related', $child->ID);`

This will return everything as it's supposed to:
`$related = apply_filters('rez_gather_related', $child);`

**Comment by jrobson153** [comment]
@drewbaker just changed the way this filter works to be a little more streamlined. Update to the latest `1.41` and then try this and let me know how it goes:

`$related = apply_filters('rez_gather_related', array(), $post);`

The filter now passes 2 args along, an array to carry all the related info to be eventually serialized and then the full post object for context. You can pass `null` to have it default to an empty array, or you could preload the $related array with some data if you need to. This way every function that uses the filter can safely assume an array is coming in.

**Comment by drewbaker** [comment]
Is it possible to have this as: `apply_filters('rez_gather_related', $post, array());` then you can leave off the last parameter most of the time. Less verbose.

**Comment by jrobson153** [comment]
Most of the time we're on the opposite end of this filter, i.e.
```
function add_something_related($related, $post){
  // do something
}
add_filter('rez_gather_related', 'add_something_related', 10, 2);
```

From this perspective it makes more sense, because the related array is what you actually need to manipulate and the context of the post variable is often not even needed.
