### ISSUE TITLE
Add Rest-easy to packagist 

### ISSUE THREAD

**Issue by PayteR** [funkhaus/Rest-Easy#29]
Hi, great idea about this plugin, but it's not that easy to install it into Bedrock installation with composer. Please add this plugin into https://packagist.org/ and add `"type": "wordpress-plugin",` into `composer.json` file https://roots.io/wordpress-plugins-with-composer/. It's easy work for just few minutes, thank you!

**Comment by SaFrMo** [comment]
Added - thanks for the heads-up and for your patience!
