### ISSUE TITLE
Add raw excerpt value to serializers

### ISSUE THREAD

**Issue by johndigital** [funkhaus/Rest-Easy#31]
Currently the excerpt field is processed, if there is an excerpt set it will be set to that but if not it will instead be set to the first 60 chars of the content, truncated and with an ellipsis added. This is good most of the time, but sometimes we don't want to show anything unless there is an excerpt set explicitly. In this scenario it would be helpful to have the raw value of the excerpt available.

**Comment by SaFrMo** [comment]
Added and documented in 91d304b!
