### ISSUE TITLE
Default $post content

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/Rest-Easy#33]
@drewbaker @johndigital @lwaldner Let's think through all the content we want on a default post and make sure it's serialized! Drew mentioned:

- [x] all attachments
- [x] all ACF content
- [x] all meta
- [x] current page ancestors

Feel free to add or edit this post if there are more!

**Comment by drewbaker** [comment]
I think it would be a good idea to add current page ancestors to site data. I need them on every site for cookie crumbs.
