### ISSUE TITLE
Querying data from custom post types

### ISSUE THREAD

**Issue by ffoerster** [funkhaus/Rest-Easy#38]
_(Not an issue, more a general question)_

I am currently looking into vuehaus + rest-easy and i really like the a lot of the ideas behind it. 

But while i know how to pull custom post type data via the wp rest api, i currently don't really know, how i would approach this with rest-easy. (i am probably just lacking the backend/php knowledge)

Sorry for clogging your issue tracker with this trivial stuff, but maybe you could give me a hint into the right direction.
Thanks in advance!

**Comment by drewbaker** [comment]
Give me an example of what you are trying to do and I'll point you in the right direction.

**Comment by ffoerster** [comment]
For example something like a custom post type archive page (e.g. for a filterable list of events):
The usual route for me would be to create a CPT, add some additional meta fields like date, time etc, expose a route to the WP REST API and do a request on the endpoint to get a list of (custom) posts and then continue working with that. 

As far as i understood the rest-easy docs, there are a lot of filters to customize the actual response, but i didn't get, how i would get a response from something, that is not a page or (default) post.

**Comment by ffoerster** [comment]
So it was really just my lack of understanding how the vuehaus router works. After working through the code, i figured out, that my "issue" is embarrassingly simple to solve.
