### ISSUE TITLE
Are there filters made for WooCommerce?

### ISSUE THREAD

**Issue by jake-101** [funkhaus/Rest-Easy#39]
I'm very impressed so far with what you guys have done. Has anyone made open source serializer filters made for WooCommerce post types? I would love to use Rest-Easy and VueHaus for a Woocommerce site.

Just thought I'd ask, thanks for all of the great work and contributions to the open source community.

**Comment by drewbaker** [comment]
@jake-101 How'd you go with this? 

I don't know anyone using this with Woo commerce, but tt would be easy enough to do that. We have it working with Shopify and a custom post type. You can see the entry point for that here:

https://github.com/funkhaus/Rest-Easy/blob/master/serializers/index.php

**Comment by jake-101** [comment]
Shopify makes it easy to pass the cart from the front-end to their hosted checkout page. I found this cart API plugin that may work in a similar fashion but I haven't had time to try it. https://wordpress.org/plugins/cart-rest-api-for-woocommerce/

How could I set up the router to go to the PHP rendered /checkout URL instead of a Vue route? I guess that is more of a VueHaus question though..

I try to use Vue or Nuxt as much as possible and will most likely use Rest-Easy at some point. You guys did make improvements to the documentation but I feel like there could be more real-world examples to solve common use cases.

I went ahead and started on it without Vue. I am using Barba.js.. it's nice but it's not Vue :-/

**Comment by jake-101** [comment]
I got a chance to try out this Co-Cart plug-in. I believe it will work for a client side WooCommerce site. It uses the wc session cookie to know what cart is being accessed and provide the missing cart API end point that WC-API doesn't have.

I am going to use it for a product configurator and will most likely attempt to make a full WooCommerce site this way at some point.
