### ISSUE TITLE
Allow API proxy

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/Rest-Easy#6]
From @jrobson153 :

> I think no matter what the ideal scenario is to just have a plugin settings page where we can just have a checkbox that's like "Site API Proxy" or something like that and put in a URL.

> My first thought is to do this 100% in Rest Easy, maybe inside the rez_build_all_data() function we can detect if that setting is on and if so just skip all the internal stuff and make a wp_remote_get() call to the proxy server and return the data.

**Comment by SaFrMo** [comment]
@jrobson153 - This might be obsolete now with [Connect to Flywheel](https://getflywheel.com/wordpress-support/connect-to-flywheel/?utm_campaign=connect-to-flywheel&utm_medium=email&utm_source=2017.11.2-local-connect-launch-(local-+-flywheel-users)&utm_content=helpdoc-cta&_hsenc=p2ANqtz-_-svLbQnGzyILjw1Bo3rO_JIm1ibVLaH1_at3xE8VTb9cfPRV-xpKMfuLxtzH7KBfPIdkXQNDvTnEUxZoRKhco_BTylA&_hsmi=58037432) - thoughts on that?

**Comment by jrobson153** [comment]
@SaFrMo Yea that's a good call. Let's hold off for now and see if we still need it.

**Comment by SaFrMo** [comment]
@jrobson153 Closing this issue for now, since Local seems to have solved it for us!
