### ISSUE TITLE
Make casing consistent 

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/Rest-Easy#8]
We should probably make sure all casing that comes out of Rest-Easy is consistent. 

For example, this: `loop[0].featured_attachment.sizes.fullscreen.html`

Should probably be this: `loop[0].featuredAttachment.sizes.fullscreen.html`

**Comment by SaFrMo** [comment]
Fixed in 8a93f3b - kept old underscore casing for backwards compatibility, but updated docs to use camel casing.
